### ISSUE TITLE
Display user's first name when logged in 

### ISSUE THREAD

**Issue by ghost** [eesazahed/vlc-grades#4]
Design Concept:
![image](https://user-images.githubusercontent.com/76220359/202065263-4ee95ca0-60d3-425e-b2a0-775e051fe206.png)

**Comment by ghost** [comment]
Maybe move the sort button under the grades?

**Comment by ghost** [comment]
Also maybe add a % sign after the grade, purely optional though as it looks fine without one

**Comment by eesazahed** [comment]
I'm happy to work on this. How can I get the users first name? Do you know? I'm not entirely sure.

**Comment by eesazahed** [comment]
completed
